name: mirrorchyan_release

on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        required: false

jobs:
  mirrorchyan:
    runs-on: macos-latest
    if: ${{ github.repository_owner == 'miaojiuqing' }}
    strategy:
      fail-fast: false
      matrix:
        os: [win, macos, linux, android]
        arch: [aarch64, x86_64]
    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: ${{ format('MaaSLIMEIM-{0}-{1}-*.zip', matrix.os, matrix.arch) }}
          mirrorchyan_rid: SLIMEIM_Maa
          tag: ${{ inputs.tag }}

          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

          owner: miaojiuqing
          repo: SLIMEIM_Maa
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
